/**
 * ACTION TYPES
 */

export const GET_USER = 'GET_USER'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_LESSONS = 'GET_LESSONS'
export const GET_MATCHING = 'GET_MATCHING'
export const LESSONS_LOADING = 'LESSONS_LOADING'

export const GET_DISCUSSION = 'GET_DISCUSSION'
export const SINGLE_DISCUSS = 'SINGLE_DISCUSS'
export const POST_DISCUSSION = 'POST_DISCUSSION'
